#!/bin/bash
# Generate compact boot context from MEMORY.md
# Usage: generate-boot.sh [MOBY_DIR]

MOBY_DIR="${1:-/data/.mobyclaw}"
BOOT_FILE="$MOBY_DIR/BOOT.md"
MEMORY_FILE="$MOBY_DIR/MEMORY.md"
NOW=$(date -u +%Y-%m-%dT%H:%M:%SZ)

if [ ! -f "$MEMORY_FILE" ]; then
  echo "No MEMORY.md found, skipping boot generation"
  exit 0
fi

cat > "$BOOT_FILE" << EOF
# Boot Context (auto-generated)
> Compact context for fast session startup. Source of truth: MEMORY.md
> Regenerated by generate-boot.sh

**Generated:** $NOW

EOF

# Extract key sections from MEMORY.md
# Identity section
sed -n '/^## Identity/,/^## /p' "$MEMORY_FILE" | head -n -1 >> "$BOOT_FILE"
echo "" >> "$BOOT_FILE"

# User section (first 10 lines)
sed -n '/^## User/,/^## /p' "$MEMORY_FILE" | head -12 >> "$BOOT_FILE"
echo "" >> "$BOOT_FILE"

# Preferences
sed -n '/^## Preferences/,/^## /p' "$MEMORY_FILE" | head -n -1 >> "$BOOT_FILE"
echo "" >> "$BOOT_FILE"

# Active tasks (IN PROGRESS only)
echo "## Unfinished Tasks" >> "$BOOT_FILE"
if grep -q "Status:\*\* IN PROGRESS" "$MEMORY_FILE"; then
  grep -B1 -A3 "Status:\*\* IN PROGRESS" "$MEMORY_FILE" >> "$BOOT_FILE"
else
  echo "- None" >> "$BOOT_FILE"
fi

echo "" >> "$BOOT_FILE"
echo "---" >> "$BOOT_FILE"
echo "*Full context in MEMORY.md*" >> "$BOOT_FILE"

echo "Boot context generated: $(wc -c < "$BOOT_FILE") bytes"
